/* Taigan Bridge — version.js (auto-generated by build.js)
 *
 * Served via jsDelivr from the latest release tag:
 *   https://cdn.jsdelivr.net/gh/beichhorn-taigan/taigan-bridge@latest/version.js
 * and read by update-check.js via cross-origin <script> injection.
 * Committed to git so jsDelivr can serve it. Static — do NOT
 * hand-edit; regenerated on every build. Commit + tag after
 * bumping package.json so jsDelivr @latest resolves to it.
 */
(function () {
  try {
    window.__TB_UPDATE_PAYLOAD__ = {
  "schema": 1,
  "stable": "1.0.3",
  "date": "2026-06-25",
  "buildHash": "13cf3122",
  "url": "https://github.com/beichhorn-taigan/taigan-bridge/releases/latest",
  "notes": null,
  "beta": null
};
  } catch (e) {}
})();
